# fly.toml app configuration file generated for rachel-portfolio on 2025-01-04T18:57:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rachel-portfolio'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[statics]]
  guest_path = "/app/dist/client"
  url_prefix = "/"

[mounts]
  source = "rachel_portfolio_data"
  destination = "/app/dist/assets"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'